# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-17 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
                ('date_created', models.DateField()),
                ('last_updated', models.DateField()),
                ('expiry', models.DateField()),
                ('priority', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Label')),
            ],
        ),
    ]
